### ISSUE TITLE
逻辑上的问题

### ISSUE THREAD

**Issue by fishjimi** [rover95/wxapp-timePicker#14]
js中的compareTime方法

          compareTime(val, type) {
			let h = val[3] ? this.data.HourList[val[3]] : "00";
			let m = val[4] ? this.data.MinuteList[val[4]] : "00";
			let s = val[5] ? this.data.SecondList[val[5]] : "00";

	// 设置时列表
	for (let i = 8; i <= 22; i++) {
		if (0 <= i && i < 10) {
		    i = "0" + i;
		}
		HourList.push(i);
	}

如果把HourList修改为8点开始而不是0点开始
则val[3]为0时,  h就取不到HourList里的值了，结果不是8而是00

**Comment by rover95** [comment]
这里逻辑上是不严谨，如果需要自定义时序，可以拷贝，转下数据类型
```
compareTime(val_, type) {    
     const val = val_.map(it=>it.toString());
```

[#14](https://github.com/rover95/wxapp-timePicker/commit/dc5812b0c65941f318d1a626b22e7dd0d0c8f6d1)
