### ISSUE TITLE
显示时间时出现的时间比当前时间小一天

### ISSUE THREAD

**Issue by wangren988888** [rover95/wxapp-timePicker#3]
配置如下:
pickerConfig: {
      endDate: false,
      column: "minute",
      dateLimit: true,
      yearStart: 2019,
      yearEnd: 2019,
      initStartTime: "2019-01-16 12:32:44",
      limitStartTime: "2019-01-16 12:32:44",
      limitEndTime: "2019-01-17 23:32:44"
    }

并且设置默认时间没有效果

**Comment by rover95** [comment]
设置initEndTime，initTime配置有最高优先级，触发滚动后再根据limitTime进行限制
